name: Run Linux.do Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '10 8 * * *'
  workflow_dispatch: # 允许手动触发
  
jobs:
  run-linuxdo:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install playwright requests tabulate configparser
        playwright install

    - name: 安装Shadowsocks客户端
      run: pip install shadowsocks

    - name: 启动Shadowsocks（通过Secrets配置）
      env:
        SS_SERVER: ${{ secrets.SS_SERVER }}
        SS_PORT: ${{ secrets.SS_PORT }}
        SS_PASSWORD: ${{ secrets.SS_PASSWORD }}
        SS_METHOD: ${{ secrets.SS_METHOD }}
      run: |
        sslocal -s $SS_SERVER -p $SS_PORT -k $SS_PASSWORD -m $SS_METHOD -l 1080 -d start

    - name: 设置代理环境变量
      run: |
        echo "HTTP_PROXY=socks5://127.0.0.1:1080" >> $GITHUB_ENV
        echo "HTTPS_PROXY=socks5://127.0.0.1:1080" >> $GITHUB_ENV


    - name: Run script
      env:
        TZ: Asia/Shanghai  # 设置时区为中国时区
        LINUXDO_USERNAME: ${{ secrets.LINUXDO_USERNAME }}
        LINUXDO_PASSWORD: ${{ secrets.LINUXDO_PASSWORD }}
        LIKE_PROBABILITY: ${{ secrets.LIKE_PROBABILITY }}
        REPLY_PROBABILITY: ${{ secrets.REPLY_PROBABILITY }}
        COLLECT_PROBABILITY: ${{ secrets.COLLECT_PROBABILITY }}
        MAX_TOPICS: ${{ secrets.MAX_TOPICS }}
        USE_WXPUSHER: ${{ secrets.USE_WXPUSHER }}
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        TOPIC_ID: ${{ secrets.TOPIC_ID }}
      run: |
        python main.py
