name: Run Linux.do Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '10 8 * * *'
  workflow_dispatch: # 允许手动触发
  
jobs:
  run-linuxdo:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install playwright requests tabulate configparser
        playwright install
        pip install pysocks

    - name: 下载 Sing-Box
      run: |
        curl -Lo sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.8.7/sing-box-1.8.7-linux-amd64.tar.gz
        tar -xzf sing-box.tar.gz --strip-components=1
        chmod +x sing-box

    - name: 生成配置文件
      env:
        SS_SERVER: ${{ secrets.SS_SERVER }}
        SS_PORT: ${{ secrets.SS_PORT }}
        SS_METHOD: ${{ secrets.SS_METHOD }}
        SS_PASSWORD: ${{ secrets.SS_PASSWORD }}
      run: |
        cat <<EOF > config.json
        {
          "inbounds": [{
            "type": "socks",
            "listen": "127.0.0.1",
            "listen_port": 1080,
            "sniff": true
          }],
          "outbounds": [{
            "type": "shadowsocks",
            "server": "$SS_SERVER",
            "server_port": $SS_PORT,
            "method": "$SS_METHOD",
            "password": "$SS_PASSWORD"
          }]
        }
        EOF

    - name: 启动 Sing-Box
      run: |
        ./sing-box run -c config.json > /dev/null 2>&1 &
        sleep 5  # 等待服务初始化

    - name: 设置全局代理环境变量
      run: |
        echo "HTTP_PROXY=socks5://127.0.0.1:1080" >> $GITHUB_ENV
        echo "HTTPS_PROXY=socks5://127.0.0.1:1080" >> $GITHUB_ENV
        echo "NO_PROXY=localhost,127.0.0.1,::1" >> $GITHUB_ENV  # 排除本地地址

    - name: Run script
      env:
        TZ: Asia/Shanghai  # 设置时区为中国时区
        LINUXDO_USERNAME: ${{ secrets.LINUXDO_USERNAME }}
        LINUXDO_PASSWORD: ${{ secrets.LINUXDO_PASSWORD }}
        LIKE_PROBABILITY: ${{ secrets.LIKE_PROBABILITY }}
        REPLY_PROBABILITY: ${{ secrets.REPLY_PROBABILITY }}
        COLLECT_PROBABILITY: ${{ secrets.COLLECT_PROBABILITY }}
        MAX_TOPICS: ${{ secrets.MAX_TOPICS }}
        USE_WXPUSHER: ${{ secrets.USE_WXPUSHER }}
        APP_TOKEN: ${{ secrets.APP_TOKEN }}
        TOPIC_ID: ${{ secrets.TOPIC_ID }}
      run: |
        python main.py
